### ISSUE TITLE
Kafka missing from Java list

### ISSUE THREAD

**Issue by akuzni2** [EvanLi/Github-Ranking#10]
Apache Kafka has more than 18K Stars as of today yet it isn't showing up on either the Java or Scala list. Kafka is primarily written in Java at this point and should be included.

https://github.com/apache/kafka

**Comment by EvanLi** [comment]
Now it's in Java top 100 list:
`2021-05-16T03:01:18Z` update
https://github.com/EvanLi/Github-Ranking/blob/25f4f1130fb3e77b72e272bbaffbb6a54f01d441/Top100/Java.md

About this issue, please see:

https://github.com/EvanLi/Github-Ranking/issues/9#issuecomment-833409975
