### ISSUE TITLE
Not update everyday

### ISSUE THREAD

**Issue by dingyunxing** [EvanLi/Github-Ranking#14]
The repo seems to haven't been updated for a while. will it be a requirments.txt available?

**Comment by EvanLi** [comment]
`Github GraphQL` query to get top 100 repos is not working. Now I have changed `100` to `60` in order to get the results on `2022-01-13`. And the data has been updated on `2022-01-13`. I will see if it will work later.

**Comment by EvanLi** [comment]
> The repo seems to haven't been updated for a while. will it be a requirments.txt available?

The repo is now updated daily. 

And requirements.txt has been available now.
