### ISSUE TITLE
Top 100 stars only shows 60!

### ISSUE THREAD

**Issue by westoque** [EvanLi/Github-Ranking#20]
https://github.com/EvanLi/Github-Ranking/blob/master/Top100/Top-100-stars.md

**Comment by ozh** [comment]
This is intentional. See 9a8a5379bdde1f4beb6c4bc279b44c95344af5aa

**Comment by gusmonod** [comment]
It may be intentional, but it is really confusing indeed. Renaming the Top 100 to be Top 60 would be a lot more logical.

**Comment by EvanLi** [comment]
As above mentioned, at this time first 100 GraphQL didn't return the results, so I had to change it to first 60.

I have fixed it to 100 since 2023-02-12. And history data has also been supplemented.
