### ISSUE TITLE
Error counting forks?

### ISSUE THREAD

**Issue by sijanec** [EvanLi/Github-Ranking#3]
This repository has the most forks: https://github.com/jtleek/datasharing

However it is not listed here as such. Why?

**Comment by EvanLi** [comment]
I use this API to get most forks repository:
`https://api.github.com/search/repositories?q=forks:%3E0&sort=forks&per_page=100`
I don't know why I didn't get this repo. 
But now it gives me the right result (datasharing is the most forks repository).
