### ISSUE TITLE
Is it possible to include Julia in the list?

### ISSUE THREAD

**Issue by ViralBShah** [EvanLi/Github-Ranking#4]
It would be great if Julia could be included in the list of languages for which top 100 list is prepared.

**Comment by EvanLi** [comment]
Julia has been added to the list since 2021-08-20 commit. 

Please refer to the link below to see more details:

https://github.com/EvanLi/Github-Ranking#julia

**Comment by EvanLi** [comment]
Julia has been added to the list since 2021-08-20 commit.

Please refer to the link below to see more details:

https://github.com/EvanLi/Github-Ranking#julia
